// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://bgnsvtaqmbbhvgrk3zlvcvncju.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fyahfdbxqzfgvhclbtcdsff5zm",
    "aws_content_delivery_bucket": "myapp-20190108192743-hostingbucket",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://myapp-20190108192743-hostingbucket.s3-website.ap-south-1.amazonaws.com"
};


export default awsmobile;
